name: Beecraft
version: '${project.version}'
main: beecraft.beecraft.BeeCraft
api-version: 1.18
authors: [ _NickV, Harumb1 ]
description: The core plugin for BeeCraft!
commands:
  help:
    description: Server help command
    aliases: [h]
  bees:
    description: Server help command
  home:
    description: Home command
  sethome:
    description: Home command
  listhomes:
    description: Home command
  delhome:
    description: Home command